// GENERATED by scripts/sitegen-sync.mjs from engine/src/sitegen/ai.mjs — edit the engine file, then run the script.
// Site Builder S3 — the AI pipeline that writes a site's texts. Pure ESM, no Node or Deno imports: the same file
// runs in the engine (own key) and in the `site-gen` Edge Function (supabase/functions/_shared/site-ai.mjs is a
// copy kept in sync by scripts/sitegen-sync.mjs).
//
// The model never writes HTML, links, icons or section ids — only words, in a fixed JSON schema. The engine's
// generator keeps the theme's structure and merges the words in (mergeContent), so a bad answer can at worst be
// dull, never broken or unsafe.
//
//   plan     (cheap model)   which sections stay, the tone, a style suggestion
//   content  (plan model)    every text of every kept section
//   review   (cheap model)   facts against the brief, lengths, repetition — corrected content
//
// `call({ step, model, system, prompt, schema, maxTokens, effort })` → `{ json, usage: { input, output, model } }`
// is supplied by the host (engine: Anthropic over the owner's key; function: the central key with metering).

export const PIPELINE_VERSION = 'site-ai/1';

/** Models by step: the cheap steps on Haiku, the writing on the plan's model (the host may override). */
export const STEP_MODELS = { plan: 'claude-haiku-4-5', content: 'claude-sonnet-5-5', review: 'claude-haiku-4-5' };
export const STEP_MAX_TOKENS = { plan: 2000, content: 16000, review: 16000 };
export const STEPS = ['plan', 'content', 'review'];

/** The longest a field may be (characters). The schema cannot carry lengths; the merge enforces them. */
export const LIMITS = { eyebrow: 60, title: 90, lead: 280, short: 120, text: 320, long: 700, label: 32, item: 200, name: 60, price: 32 };

const LANG_NAMES = { bg: 'Bulgarian', en: 'English' };

export const SYSTEM = `You write the texts of small business websites for people who are not writers or programmers.

Rules you never break:
- Write only what the brief supports. Never invent facts: no made-up reviews, client names, numbers, years of experience, awards, prices or addresses. If a section needs facts the brief does not give (reviews, stats, team), drop that section (keep: false) instead of inventing.
- Write in the site's language, in the owner's voice: warm, concrete, confident, no marketing clichés ("unlock your potential", "we go the extra mile"), no exclamation marks, no emoji.
- Short beats long. Headings under 8 words. One idea per sentence. The reader decides in 5 seconds whether this is for them.
- Keep the structure you are given: the same pages, the same sections in the same order, the same number of items in a list unless told the list may shrink or grow. Buttons keep their meaning (a "book" button stays a booking button).
- Never include HTML, Markdown, links, email addresses or phone numbers in the text — the site adds those itself. Emphasis in a title is allowed as *words between asterisks*, at most once per title.
- Answer only with JSON that matches the schema. No commentary.`;

// ---------------------------------------------------------------- schemas (structured outputs: additionalProperties false everywhere, no lengths)

const str = { type: 'string' };
const nul = { type: 'null' };
const nstr = { anyOf: [str, nul] };
const strList = { type: 'array', items: str };
const rows = { type: 'array', items: strList };
const obj = (properties) => ({ type: 'object', properties, required: Object.keys(properties), additionalProperties: false });

export const PLAN_SCHEMA = obj({
  tone: str,
  styleSuggestion: { anyOf: [{ type: 'string', enum: ['calm', 'bold', 'elegant'] }, nul] },
  sections: { type: 'array', items: obj({ page: str, index: { type: 'integer' }, keep: { type: 'boolean' }, note: nstr }) },
});

const SECTION_SCHEMA = obj({
  index: { type: 'integer' },
  keep: { type: 'boolean' },
  title: nstr,
  intro: nstr,
  h: nstr,
  p: nstr,
  button: nstr,
  items: { anyOf: [rows, nul] },
  plans: { anyOf: [{ type: 'array', items: obj({ name: str, price: str, per: nstr, featured: nstr, features: strList, cta: nstr }) }, nul] },
  groups: { anyOf: [{ type: 'array', items: obj({ name: str, items: rows }) }, nul] },
  posts: { anyOf: [{ type: 'array', items: obj({ tag: str, date: str, h: str, p: str }) }, nul] },
  body: { anyOf: [strList, nul] },
  send: nstr,
  note: nstr,
});

export const CONTENT_SCHEMA = obj({
  description: str,
  tagline: str,
  nav: strList,
  headerCta: nstr,
  pages: {
    type: 'array',
    items: obj({
      id: str,
      title: nstr,
      description: nstr,
      pagehead: { anyOf: [strList, nul] },
      hero: { anyOf: [obj({ eyebrow: nstr, title: str, lead: str, cta: nstr, cta2: nstr, cardTitle: nstr, cardRows: { anyOf: [rows, nul] }, cardNote: nstr, chips: { anyOf: [strList, nul] } }), nul] },
      sections: { type: 'array', items: SECTION_SCHEMA },
    }),
  },
});

// ---------------------------------------------------------------- the brief and the recipe as the model sees them

const clip = (s, n) => (typeof s === 'string' ? s.trim().slice(0, n) : '');

/** The brief as a short, factual block. Contacts are named but never quoted (the site renders them itself). */
export function briefText(brief) {
  const lines = [`Site name: ${clip(brief.name, 80)}`, `Language: ${LANG_NAMES[brief.lang] || brief.lang}`];
  if (brief.description) lines.push(`One-line description: ${clip(brief.description, 300)}`);
  if (brief.offer) lines.push(`What they offer, in their words: ${clip(brief.offer, 1200)}`);
  if (brief.audience) lines.push(`Who it is for: ${clip(brief.audience, 200)}`);
  if (Array.isArray(brief.services) && brief.services.length) {
    lines.push('Services or programs (names and prices are facts — keep them exactly):');
    for (const s of brief.services) lines.push(`- ${clip(s.name, 80)}${s.price ? ` — ${clip(s.price, 40)}` : ''}${s.text ? `: ${clip(s.text, 240)}` : ''}`);
  }
  const c = brief.contacts || {};
  const has = ['email', 'phone', 'address', 'instagram', 'website'].filter((k) => c[k]);
  lines.push(has.length ? `Contact channels the site shows: ${has.join(', ')} (do not write the values).` : 'No contact details were given.');
  lines.push(Array.isArray(brief.photos) && brief.photos.length ? `Photos: ${brief.photos.length} (the first goes at the top of the page).` : 'No photos: sections that only make sense with photos may be dropped.');
  if (brief.style) lines.push(`Chosen style: ${brief.style}.`);
  return lines.join('\n');
}

/** What each section holds today — enough for the model to rewrite it, without HTML, links or icons. */
function describeSection(s) {
  const d = { type: s.type };
  if (s.title) d.title = s.title;
  if (s.intro) d.intro = s.intro;
  if (s.h) d.h = s.h;
  if (s.p) d.p = s.p;
  if (Array.isArray(s.button)) d.button = s.button[0];
  if (Array.isArray(s.items)) d.items = s.items.map((it) => (Array.isArray(it) ? (s.type === 'cards' ? it.slice(1) : it) : typeof it === 'object' && it ? [it.name || it.h || '', it.price || it.p || ''] : [String(it)]));
  if (s.type === 'pricing' || s.type === 'programs') d.plans = (s.items || []).map((p) => ({ name: p.name, price: p.price, per: p.per || null, featured: p.featured || null, features: p.features || [], cta: Array.isArray(p.cta) ? p.cta[0] : null }));
  if (s.type === 'menu') d.groups = (s.groups || []).map((g) => ({ name: g.name, items: g.items || [] }));
  if (s.type === 'posts') d.posts = (s.items || []).map((p) => ({ tag: p.tag, date: p.date, h: p.h, p: p.p }));
  if (s.type === 'article') d.body = s.body || [];
  if (s.send) d.send = s.send;
  if (s.note) d.note = s.note;
  if (s.messageLabel) d.messageLabel = s.messageLabel;
  if (s.hoursTitle) d.hoursTitle = s.hoursTitle;
  return d;
}

export function recipeText(content) {
  const out = { tagline: content.tagline, description: content.description, nav: (content.nav || []).map((n) => n[0]), headerCta: content.headerCta ? content.headerCta[0] : null, pages: [] };
  for (const [id, p] of Object.entries(content.pages || {})) {
    const page = { id, title: p.title || null, description: p.description || null, pagehead: p.pagehead || null, hero: null, sections: [] };
    if (p.hero) {
      const h = p.hero;
      page.hero = { eyebrow: h.eyebrow || null, title: h.title, lead: h.lead, cta: Array.isArray(h.cta) ? h.cta[0] : null, cta2: Array.isArray(h.cta2) ? h.cta2[0] : null, cardTitle: h.card?.title || null, cardRows: h.card?.rows || null, cardNote: h.card?.note || null, chips: h.chips || null };
    }
    page.sections = (p.sections || []).map((s, index) => ({ index, ...describeSection(s) }));
    out.pages.push(page);
  }
  return JSON.stringify(out, null, 1);
}

// ---------------------------------------------------------------- prompts

export function planPrompt(brief, recipe) {
  return `${briefText(brief)}

The site is built from this recipe (the sample texts show what each section is for):
${recipeText(recipe)}

Decide for every section whether it stays (keep) given what the brief supports — drop reviews, stats, team or gallery sections the brief has no facts or photos for; keep contact, pricing and the hero. Describe the tone in one sentence. Suggest a style (calm, bold, elegant) or null to keep the theme's own.`;
}

export function contentPrompt(brief, recipe, plan) {
  const kept = plan ? plan.sections.filter((s) => s.keep).map((s) => `${s.page}#${s.index}`) : null;
  return `${briefText(brief)}
${plan?.tone ? `\nTone: ${clip(plan.tone, 200)}` : ''}

Rewrite every text of this recipe for this owner. Keep the structure; mark a section keep: false only when it must go${kept ? ` (these stay: ${kept.join(', ')})` : ''}. Lists keep their number of items unless the brief gives a different number of services. Prices and service names come from the brief verbatim. The "items" rows keep their column meaning (for cards: [heading, text]; steps: [heading, text]; quotes: [quote, who]; faq: [question, answer]; stats: [number, label]; prose/story: [heading, paragraph]; chips/gallery: [caption]).

Recipe:
${recipeText(recipe)}`;
}

export function reviewPrompt(brief, content) {
  return `${briefText(brief)}

Review this site content against the brief and fix it in place:
- remove or neutralise any fact the brief does not support (invented numbers, reviews, names, years, awards, addresses); a section that only works with such facts gets keep: false;
- shorten: titles under 8 words, leads under 2 sentences, list items under 25 words;
- remove repetition between sections and any HTML, Markdown links, emails or phone numbers;
- keep the language, the structure, the service names and prices exactly.
Return the corrected content in the same schema.

Content:
${JSON.stringify(content)}`;
}

// ---------------------------------------------------------------- merge: the model's words into the recipe

const cut = (v, n) => (typeof v === 'string' && v.trim() ? v.trim().replace(/<[^>]*>/g, '').slice(0, n) : null);
const cutRows = (v, n) => (Array.isArray(v) ? v.filter(Array.isArray).map((r) => r.map((c) => cut(c, n) || '')) : null);

/** Sections the AI may add items to or shrink: the owner's services decide the count. */
const FLEX = new Set(['cards', 'audience', 'pricing', 'programs', 'faq', 'steps', 'chips', 'quotes', 'stats']);

function mergeSection(base, ai) {
  const s = { ...base };
  const type = s.type;
  const title = cut(ai.title, LIMITS.title);
  const intro = cut(ai.intro, LIMITS.text);
  if (s.title !== undefined && title) s.title = title;
  if (intro && (s.intro !== undefined || title)) s.intro = intro;
  if (type === 'cta' || type === 'booking') {
    if (cut(ai.h, LIMITS.title)) s.h = cut(ai.h, LIMITS.title);
    if (cut(ai.p, LIMITS.text)) s.p = cut(ai.p, LIMITS.text);
    if (Array.isArray(s.button) && cut(ai.button, LIMITS.label)) s.button = [cut(ai.button, LIMITS.label), s.button[1]];
    return s;
  }
  if (type === 'pricing' || type === 'programs') {
    if (Array.isArray(ai.plans) && ai.plans.length) {
      const old = s.items || [];
      s.items = ai.plans.slice(0, 6).map((p, i) => {
        const o = old[i] || old[0] || {};
        return { ...o, name: cut(p.name, LIMITS.name) || o.name || '', price: cut(p.price, LIMITS.price) || o.price || '', per: cut(p.per, LIMITS.label) || undefined, featured: cut(p.featured, LIMITS.label) || undefined, features: (Array.isArray(p.features) ? p.features : o.features || []).map((f) => cut(f, LIMITS.item) || '').filter(Boolean).slice(0, 8), cta: Array.isArray(o.cta) ? [cut(p.cta, LIMITS.label) || o.cta[0], o.cta[1]] : o.cta };
      });
    }
    return s;
  }
  if (type === 'menu') {
    if (Array.isArray(ai.groups) && ai.groups.length) s.groups = ai.groups.slice(0, 8).map((g) => ({ name: cut(g.name, LIMITS.name) || '', items: (cutRows(g.items, LIMITS.item) || []).slice(0, 20) }));
    return s;
  }
  if (type === 'posts') {
    if (Array.isArray(ai.posts) && ai.posts.length) {
      const old = s.items || [];
      s.items = ai.posts.slice(0, old.length || 6).map((p, i) => ({ ...(old[i] || old[0] || {}), tag: cut(p.tag, LIMITS.label) || '', date: cut(p.date, LIMITS.label) || '', h: cut(p.h, LIMITS.title) || '', p: cut(p.p, LIMITS.text) || '' }));
    }
    return s;
  }
  if (type === 'article') {
    if (cut(ai.h, LIMITS.title)) s.h = cut(ai.h, LIMITS.title);
    if (Array.isArray(ai.body) && ai.body.length) s.body = ai.body.map((b) => cut(b, LIMITS.long) || '').filter(Boolean).slice(0, 40);
    return s;
  }
  if (type === 'contact') {
    if (cut(ai.send, LIMITS.label)) s.send = cut(ai.send, LIMITS.label);
    return s;
  }
  if (type === 'form') {
    if (cut(ai.button, LIMITS.label)) s.button = cut(ai.button, LIMITS.label);
    if (cut(ai.note, LIMITS.short)) s.note = cut(ai.note, LIMITS.short);
    return s;
  }
  // list sections: rows of text, icons and extra columns kept from the recipe
  const aiRows = cutRows(ai.items, LIMITS.item);
  if (aiRows && aiRows.length && Array.isArray(s.items)) {
    const old = s.items;
    const count = FLEX.has(type) ? Math.min(aiRows.length, 12) : Math.min(old.length, aiRows.length);
    s.items = aiRows.slice(0, count).map((r, i) => {
      const o = old[i] ?? old[old.length - 1];
      if (type === 'cards' || type === 'audience') return [Array.isArray(o) ? o[0] : 'spark', r[0] || '', r[1] || ''];
      if (type === 'chips' || type === 'gallery') return r[0] || '';
      if (Array.isArray(o)) return o.map((cell, j) => r[j] ?? (j < r.length ? '' : cell));
      return r;
    });
  }
  return s;
}

/**
 * The recipe (one language, already carrying the owner's services/contacts/photos) with the AI's words merged in.
 * Nothing structural comes from the model: hrefs, icons, ids, form fields, hours and rows stay.
 */
export function mergeContent(base, ai) {
  const out = JSON.parse(JSON.stringify(base));
  if (cut(ai.description, LIMITS.text)) out.description = cut(ai.description, LIMITS.text);
  if (cut(ai.tagline, LIMITS.short)) out.tagline = cut(ai.tagline, LIMITS.short);
  if (Array.isArray(ai.nav) && Array.isArray(out.nav) && ai.nav.length === out.nav.length) out.nav = out.nav.map((n, i) => [cut(ai.nav[i], LIMITS.label) || n[0], n[1]]);
  if (Array.isArray(out.headerCta) && cut(ai.headerCta, LIMITS.label)) out.headerCta = [cut(ai.headerCta, LIMITS.label), out.headerCta[1]];
  for (const p of Array.isArray(ai.pages) ? ai.pages : []) {
    const page = out.pages?.[p.id];
    if (!page) continue;
    if (page.title !== undefined && cut(p.title, LIMITS.title)) page.title = cut(p.title, LIMITS.title);
    if (page.description !== undefined && cut(p.description, LIMITS.text)) page.description = cut(p.description, LIMITS.text);
    if (Array.isArray(page.pagehead) && Array.isArray(p.pagehead) && p.pagehead.length >= 2) page.pagehead = [cut(p.pagehead[0], LIMITS.title) || page.pagehead[0], cut(p.pagehead[1], LIMITS.text) || page.pagehead[1]];
    if (page.hero && p.hero) {
      const h = page.hero;
      const a = p.hero;
      if (h.eyebrow !== undefined) h.eyebrow = cut(a.eyebrow, LIMITS.eyebrow) || h.eyebrow;
      h.title = cut(a.title, LIMITS.title) || h.title;
      h.lead = cut(a.lead, LIMITS.lead) || h.lead;
      if (Array.isArray(h.cta) && cut(a.cta, LIMITS.label)) h.cta = [cut(a.cta, LIMITS.label), h.cta[1]];
      if (Array.isArray(h.cta2) && cut(a.cta2, LIMITS.label)) h.cta2 = [cut(a.cta2, LIMITS.label), h.cta2[1]];
      if (h.card) {
        if (cut(a.cardTitle, LIMITS.short)) h.card.title = cut(a.cardTitle, LIMITS.short);
        const r = cutRows(a.cardRows, LIMITS.short);
        if (r && r.length) h.card.rows = r.slice(0, 5).map((row) => [row[0] || '', row[1] || '']);
        if (a.cardNote !== undefined) h.card.note = cut(a.cardNote, LIMITS.short) || undefined;
      }
      if (Array.isArray(h.chips) && Array.isArray(a.chips) && a.chips.length) h.chips = a.chips.map((c) => cut(c, LIMITS.label) || '').filter(Boolean).slice(0, 12);
    }
    const sections = page.sections || [];
    const next = [];
    const byIndex = new Map((Array.isArray(p.sections) ? p.sections : []).map((s) => [s.index, s]));
    sections.forEach((s, index) => {
      const ai = byIndex.get(index);
      if (!ai) return next.push(s);
      if (ai.keep === false && !['contact', 'cta', 'booking', 'form'].includes(s.type)) return;
      next.push(mergeSection(s, ai));
    });
    page.sections = next;
  }
  return out;
}

// ---------------------------------------------------------------- the pipeline

/** Problems in a content answer; [] when it is usable. */
export function validateContent(ai) {
  const errors = [];
  if (!ai || typeof ai !== 'object') return ['not an object'];
  if (!Array.isArray(ai.pages) || !ai.pages.length) errors.push('no pages');
  for (const p of ai.pages || []) {
    if (!p || typeof p.id !== 'string') errors.push('page without id');
    if (p?.hero && (typeof p.hero.title !== 'string' || !p.hero.title.trim())) errors.push(`${p.id}: hero without title`);
    if (!Array.isArray(p?.sections)) errors.push(`${p?.id}: sections missing`);
  }
  return errors;
}

/**
 * Runs the three steps. `recipe` = the theme's content for the brief's language with the owner's details already
 * applied (brief.mjs applyBrief); the result is the same shape with the AI's words. `models` may override the
 * step models (the function picks by plan); `onStep(id, status, info)` reports progress.
 */
export async function runPipeline({ brief, recipe, call, models = {}, onStep = () => {} }) {
  const usage = { input: 0, output: 0, steps: {} };
  const use = (step, u) => {
    usage.input += u?.input || 0;
    usage.output += u?.output || 0;
    usage.steps[step] = { input: u?.input || 0, output: u?.output || 0, model: u?.model || null };
  };
  const model = (step) => models[step] || STEP_MODELS[step];

  onStep('plan', 'running', { model: model('plan') });
  let plan = null;
  try {
    const r = await call({ step: 'plan', model: model('plan'), system: SYSTEM, prompt: planPrompt(brief, recipe), schema: PLAN_SCHEMA, maxTokens: STEP_MAX_TOKENS.plan, effort: 'low' });
    use('plan', r.usage);
    plan = r.json && Array.isArray(r.json.sections) ? r.json : null;
    onStep('plan', 'pass', { model: r.usage?.model || model('plan') });
  } catch (e) {
    // the plan is advice; the content step can decide alone
    onStep('plan', 'warn', { error: e.message });
  }

  onStep('content', 'running', { model: model('content') });
  const c = await call({ step: 'content', model: model('content'), system: SYSTEM, prompt: contentPrompt(brief, recipe, plan), schema: CONTENT_SCHEMA, maxTokens: STEP_MAX_TOKENS.content, effort: 'medium' });
  use('content', c.usage);
  const problems = validateContent(c.json);
  if (problems.length) {
    onStep('content', 'fail', { error: problems.join('; ') });
    throw Object.assign(new Error(`content step returned an unusable answer: ${problems.join('; ')}`), { code: 'ai_bad_answer' });
  }
  onStep('content', 'pass', { model: c.usage?.model || model('content') });

  onStep('review', 'running', { model: model('review') });
  let reviewed = c.json;
  try {
    const r = await call({ step: 'review', model: model('review'), system: SYSTEM, prompt: reviewPrompt(brief, c.json), schema: CONTENT_SCHEMA, maxTokens: STEP_MAX_TOKENS.review, effort: 'low' });
    use('review', r.usage);
    if (!validateContent(r.json).length) reviewed = r.json;
    onStep('review', 'pass', { model: r.usage?.model || model('review') });
  } catch (e) {
    onStep('review', 'warn', { error: e.message }); // the unreviewed content is still a real site
  }

  const content = mergeContent(recipe, reviewed);
  return { content, plan, usage, styleSuggestion: plan?.styleSuggestion || null, version: PIPELINE_VERSION };
}
