#!/usr/bin/env bash
# One command to save work: commit everything → push to GitHub → backup on this computer.
#   scripts/team/save.sh                    automatic message from what changed
#   scripts/team/save.sh "Pricing: yearly toggle"
#   scripts/team/save.sh --auto             used by the Claude Code hook (quiet when there is nothing to save)
# Never commits on main: work on main is moved to a new branch first. Never commits keys (secret-guard.sh).
set -u
auto=0
msg=""
for a in "$@"; do
  case "$a" in
    --auto) auto=1 ;;
    *) msg="$a" ;;
  esac
done

root=$(git rev-parse --show-toplevel 2>/dev/null) || { echo "Not inside the beforeideploy repository."; exit 1; }
cd "$root" || exit 1
here="$root/scripts/team"

# a merge, rebase or cherry-pick in progress is for a person to finish
for f in MERGE_HEAD REBASE_HEAD CHERRY_PICK_HEAD; do
  [ -e "$(git rev-parse --git-dir)/$f" ] && { echo "⏸  A git $f is in progress — finish it first, then save."; exit 0; }
done

if [ -z "$(git status --porcelain)" ]; then
  [ $auto -eq 1 ] && exit 0
  echo "✅ Nothing new to save."
  bash "$here/backup.sh"
  exit 0
fi

branch=$(git symbolic-ref --short -q HEAD) || { echo "⏸  No branch is checked out (detached HEAD). Run: git switch -c <name>"; exit 0; }
case "$branch" in
  main|master)
    who=$(git config user.name 2>/dev/null | tr 'A-Z ' 'a-z-' | tr -cd 'a-z0-9-')
    branch="wip/${who:-me}-$(date +%Y%m%d-%H%M)"
    git switch -q -c "$branch"
    echo "↪︎  main is protected — your changes moved to the new branch $branch"
    ;;
esac

git add -A
if ! bash "$here/secret-guard.sh"; then
  git reset -q
  exit 3
fi
[ -z "$(git diff --cached --name-only)" ] && exit 0

# which parts of the product changed → readable commit message
areas=$(git diff --cached --name-only | awk -F/ '
  $1=="App"||$1=="packaging"            {a["mac"]=1; next}
  $1=="desktop"                         {a["desktop"]=1; next}
  $0 ~ /^engine\/src\/platform\/win32/  {a["windows"]=1; next}
  $0 ~ /^engine\/src\/platform\/linux/  {a["linux"]=1; next}
  $0 ~ /^engine\/src\/platform\/darwin/ {a["mac"]=1; next}
  $1=="site"||$0=="scripts/site-build.py" {a["site"]=1; next}
  $1=="web"                             {a["web"]=1; next}
  $1=="design"                          {a["design"]=1; next}
  $1=="engine"                          {a["engine"]=1; next}
  $1=="supabase"                        {a["cloud"]=1; next}
  $1=="docs"||$0 ~ /\.md$/              {a["docs"]=1; next}
  $1=="tests"                           {a["tests"]=1; next}
  {a["repo"]=1}
  END {s=""; for (k in a) s = s (s==""?"":",") k; print s}')
n=$(git diff --cached --name-only | wc -l | tr -d ' ')
if [ -z "$msg" ]; then
  files=$(git diff --cached --name-only | head -3 | sed 's#.*/##' | paste -sd, - | sed 's/,/, /g')
  [ "$n" -gt 3 ] && files="$files and $((n - 3)) more"
  msg="save($areas): $files"
fi

if git diff --cached --name-only | grep -qE '^site/.*\.html$' && ! git diff --cached --name-only | grep -q '^scripts/site-build.py$'; then
  echo "ℹ️  site/*.html is generated by scripts/site-build.py — change the generator too, or the next build overwrites the edit."
fi

BID_SAVING=1 git commit -q -m "$msg" || { echo "⚠️  Commit failed."; exit 1; }
echo "📝 Saved $n file(s) on $branch: $msg"

# push, retrying a flaky network (2s, 4s, 8s)
pushed=0
for wait in 0 2 4 8; do
  [ "$wait" -gt 0 ] && sleep "$wait"
  if git push -q -u origin "$branch" 2>/dev/null; then pushed=1; break; fi
done
if [ $pushed -eq 1 ]; then
  echo "☁️  Pushed to GitHub ($branch)"
else
  echo "⚠️  Not pushed (offline?). The commit is safe locally — the next save pushes it."
fi

bash "$here/backup.sh"
exit 0
