#!/usr/bin/env node
// engine/src/sitegen/ai.mjs (the Site Builder AI pipeline) is the only editable source; the `site-gen` Edge
// Function runs a byte-identical copy from supabase/functions/_shared/site-ai.mjs. --check is run in CI.
import fs from 'node:fs';
const root = new URL('../', import.meta.url);
const src = fs.readFileSync(new URL('engine/src/sitegen/ai.mjs', root), 'utf8');
const header = '// GENERATED by scripts/sitegen-sync.mjs from engine/src/sitegen/ai.mjs — edit the engine file, then run the script.\n';
const want = header + src;
const dst = new URL('supabase/functions/_shared/site-ai.mjs', root);
const have = fs.existsSync(dst) ? fs.readFileSync(dst, 'utf8') : '';
if (process.argv.includes('--check')) {
  if (have !== want) { console.error('Run node scripts/sitegen-sync.mjs (site-ai.mjs differs from engine/src/sitegen/ai.mjs)'); process.exit(1); }
  console.log('site-ai.mjs matches the engine source.');
} else {
  fs.writeFileSync(dst, want);
  console.log('site-ai.mjs updated.');
}
