// Generates web/src/styles/tokens.css from design/tokens.json (one source for web, desktop and site).
// `--check` fails when the generated file is out of date (used in CI).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(fs.readFileSync(path.join(ROOT, 'design', 'tokens.json'), 'utf8'));
const OUT = path.join(ROOT, 'web', 'src', 'styles', 'tokens.css');
const v = (k) => `--${k.replace(/\./g, '-')}`;

function css() {
  const light = [], dark = [], common = [];
  for (const [k, c] of Object.entries(tokens.color)) { light.push(`  ${v('c.' + k)}: ${c.light};`); dark.push(`  ${v('c.' + k)}: ${c.dark};`); }
  for (const [k, e] of Object.entries(tokens.elevation)) { light.push(`  ${v('shadow.' + k)}: ${e.light};`); dark.push(`  ${v('shadow.' + k)}: ${e.dark};`); }
  common.push(`  --font-ui: ${tokens.font['family.ui']};`, `  --font-mono: ${tokens.font['family.mono']};`);
  for (const [k, px] of Object.entries(tokens.font.size)) common.push(`  --fs-${k}: ${px}px;`, `  --fw-${k}: ${tokens.font.weight[k]};`);
  for (const [k, px] of Object.entries(tokens.space)) common.push(`  --sp-${k}: ${px}px;`);
  for (const [k, px] of Object.entries(tokens.radius)) common.push(`  --r-${k}: ${px}px;`);
  for (const [k, val] of Object.entries(tokens.motion)) common.push(`  --motion-${k}: ${val};`);
  for (const [k, px] of Object.entries(tokens.layout)) common.push(`  ${v('layout.' + k)}: ${px}px;`);
  return `/* GENERATED by scripts/tokens-build.mjs from design/tokens.json — do not edit by hand. */
:root {
${common.join('\n')}
${light.join('\n')}
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${dark.map((l) => '  ' + l).join('\n')}
    color-scheme: dark;
  }
}
:root[data-theme="dark"] {
${dark.join('\n')}
  color-scheme: dark;
}
@media (prefers-reduced-motion: reduce) {
  :root { --motion-quick: 0ms; --motion-panel: 0ms; --motion-standard: 0ms; }
}
`;
}

const next = css();
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== next) { console.error('tokens.css is out of date — run: node scripts/tokens-build.mjs'); process.exit(1); }
  console.log('✅ tokens up to date');
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, next);
  console.log('wrote', path.relative(ROOT, OUT));
}
