-- Generated catalog migration (v13). Preserves existing Paddle IDs and unrelated settings.
-- Existing subscribers retain their provider prices. Reconcile sandbox IDs in Admin before enabling sales.
do $$
declare old_catalog jsonb; next_catalog jsonb := '{"version":"v13","currency":"EUR","taxInclusive":true,"mode":"sandbox","features":{"hostingIncluded":false},"trial":{"days":7,"plan":"high","tokens":50000,"activeSites":1},"release":{"hours":336,"guard24hShare":0.25,"guard7dShare":0.5,"packCreditsPerHour":200000},"starterBonus":{"credits":60000,"validityDays":30,"oncePer":"customer","actions":["ai.fix","ai.fix.deep","ai.site.create","ai.site.edit"]},"free":{"price":0,"credits":10000,"activeSites":1,"activeSitesMax":1,"validityMonths":1,"cloudMinutes":0,"hosting":{"provider":"netlify","tier":"free","credits":300,"paidBy":"customer"}},"plans":{"flash":{"price":9.99,"paddlePriceId":null,"yearly":{"price":99.9,"paddlePriceId":null},"hostingIncluded":{"price":14.99,"paddlePriceId":null,"yearly":{"price":183.9,"paddlePriceId":null,"domain":true}},"credits":40000,"activeSites":1,"activeSitesMax":1,"validityMonths":1,"cloudMinutes":300,"hosting":{"provider":"netlify","tier":"personal","credits":1000},"extras":{"domain":false,"netlifyCredits":false,"boost":false}},"high":{"price":29.99,"paddlePriceId":null,"yearly":{"price":299.9,"paddlePriceId":null},"hostingIncluded":{"price":29.99,"paddlePriceId":null,"yearly":{"price":358.9,"paddlePriceId":null,"domain":true}},"credits":100000,"activeSites":3,"activeSitesMax":3,"validityMonths":3,"cloudMinutes":1000,"hosting":{"provider":"netlify","tier":"pro","credits":3000},"extras":{"domain":false,"netlifyCredits":false,"boost":false}},"knight":{"price":99.99,"paddlePriceId":null,"yearly":{"price":999.9,"paddlePriceId":null},"hostingIncluded":{"price":99.99,"paddlePriceId":null,"yearly":{"price":1089.9,"paddlePriceId":null,"domain":true}},"credits":800000,"activeSites":10,"activeSitesMax":25,"validityMonths":10,"cloudMinutes":4000,"hosting":{"provider":"netlify","tier":"pro","credits":5000},"extras":{"domain":true,"netlifyCredits":false,"boost":false}}},"packs":[{"id":"pack-100k","tokens":100000,"price":4.99,"validityMonths":12,"paddlePriceId":null},{"id":"pack-500k","tokens":500000,"price":19.99,"validityMonths":12,"paddlePriceId":null},{"id":"pack-1m","tokens":1000000,"price":39.99,"validityMonths":12,"paddlePriceId":null}]}'::jsonb; old_plans jsonb; tier text; pack jsonb; old_pack jsonb; packs jsonb := '[]'::jsonb;
begin
  select value into old_catalog from public.settings where key = 'billing.catalog';
  if old_catalog->>'version' = next_catalog->>'version' then return; end if;
  foreach tier in array array['flash','high','knight'] loop
    next_catalog := jsonb_set(next_catalog, array['plans',tier,'paddlePriceId'], coalesce(old_catalog #> array['plans',tier,'paddlePriceId'], 'null'::jsonb));
    next_catalog := jsonb_set(next_catalog, array['plans',tier,'yearly','paddlePriceId'], coalesce(old_catalog #> array['plans',tier,'yearly','paddlePriceId'], 'null'::jsonb));
    next_catalog := jsonb_set(next_catalog, array['plans',tier,'needsReconciliation'], to_jsonb(coalesce(old_catalog #>> array['plans',tier,'price'],'') <> next_catalog #>> array['plans',tier,'price']));
    next_catalog := jsonb_set(next_catalog, array['plans',tier,'yearly','needsReconciliation'], to_jsonb(coalesce(old_catalog #>> array['plans',tier,'yearly','price'],'') <> next_catalog #>> array['plans',tier,'yearly','price']));
    if next_catalog #> array['plans',tier,'hostingIncluded'] is not null then
      next_catalog := jsonb_set(next_catalog, array['plans',tier,'hostingIncluded','paddlePriceId'], coalesce(old_catalog #> array['plans',tier,'hostingIncluded','paddlePriceId'], 'null'::jsonb));
      next_catalog := jsonb_set(next_catalog, array['plans',tier,'hostingIncluded','yearly','paddlePriceId'], coalesce(old_catalog #> array['plans',tier,'hostingIncluded','yearly','paddlePriceId'], 'null'::jsonb));
      next_catalog := jsonb_set(next_catalog, array['plans',tier,'hostingIncluded','needsReconciliation'], to_jsonb(coalesce(old_catalog #>> array['plans',tier,'hostingIncluded','price'],'') <> next_catalog #>> array['plans',tier,'hostingIncluded','price']));
      next_catalog := jsonb_set(next_catalog, array['plans',tier,'hostingIncluded','yearly','needsReconciliation'], to_jsonb(coalesce(old_catalog #>> array['plans',tier,'hostingIncluded','yearly','price'],'') <> next_catalog #>> array['plans',tier,'hostingIncluded','yearly','price']));
    end if;
  end loop;
  for pack in select * from jsonb_array_elements(next_catalog->'packs') loop
    select value into old_pack from jsonb_array_elements(coalesce(old_catalog->'packs','[]'::jsonb)) where value->>'id' = pack->>'id' limit 1;
    packs := packs || jsonb_build_array(pack || jsonb_build_object('paddlePriceId',coalesce(old_pack->'paddlePriceId','null'::jsonb),'needsReconciliation',coalesce(old_pack->>'price','') <> pack->>'price'));
  end loop;
  next_catalog := jsonb_set(next_catalog, '{packs}', packs);
  insert into public.settings(key,value) values ('billing.catalog',coalesce(old_catalog,'{}'::jsonb) || next_catalog) on conflict(key) do update set value=excluded.value;
  select value into old_plans from public.settings where key='plans';
  insert into public.settings(key,value) values ('plans',coalesce(old_plans,'{}'::jsonb) || '{"free":{"tokens":10000,"max_active_sites":1,"fair_use_sites":1,"validity_months":1,"cloud_minutes":0},"flash":{"tokens":40000,"max_active_sites":1,"fair_use_sites":1,"validity_months":1,"cloud_minutes":300},"high":{"tokens":100000,"max_active_sites":3,"fair_use_sites":3,"validity_months":3,"cloud_minutes":1000},"knight":{"tokens":800000,"max_active_sites":10,"fair_use_sites":25,"validity_months":10,"cloud_minutes":4000}}'::jsonb) on conflict(key) do update set value=excluded.value;
end $$;
